[window]

opacity = 0.6

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 11

[colors.primary]
foreground = "#dddddd"
background = "#000022"

[colors.normal]
black = "#000000"
red = "#dd1111"
green = "#11dd11"
yellow = "#dddd11"
blue = "#1111dd"
magenta = "#dd11dd"
cyan = "#11dddd"
white = "#dddddd"

[colors.bright]
black = "#767676"
red = "#ff7676"
green = "#76ff76"
yellow = "#ffff76"
blue = "#7676ff"
magenta = "#ff76ff"
cyan = "#76ffff"
white = "#ffffff"
